name: "Generate Version"
description: "Get the dependencies (via npm) and cache them."
inputs:
  prefix-tag:
    description: "The service name so it can be distinguised in tags"
    required: true
  github-token:
    description: "Github token"
    required: true
outputs:
  new-tag:
    description: "The new bumped version"
    value: ${{ steps.new-tag.outputs.generated-tag }}
runs:
  using: "composite" #important its named correct
  steps:
    - name: Print prefix
      run: echo ${{inputs.prefix-tag}}
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
    - name: Path Tag Bumper
      id: tag-bumper
      uses: gls-denmark/path-tag-bumper@1.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        prefix-tag: ${{ inputs.prefix-tag }}
        github-token: ${{ inputs.github-token }}
    - name: Print New Tag
      id: new-tag
      run: echo "::set-output name=generated-tag::${{steps.tag-bumper.outputs.new-tag}}"
      shell: bash
